env:
  global:
    - CC_TEST_REPORTER_ID=aee1d6c4ea3c4f7831fe7a06afca6ac301027aea50c282a0694e911aa38d34be
rvm:
  - 3.0.0
  - 2.7.2
  - 2.6.6
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
cache: bundler
script:
  - bundle exec rake spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
